export type BoardSize = "small" | "medium" | "large"
export type CardSetKey =
  | "animals"
  | "fruits"
  | "cartoon"
  | "mixed"
  | "custom"
  | "cards"
  | "cars"

export const CARD_SETS: Record<Exclude<CardSetKey, "custom">, string[]> = {
  animals: [
    "animals/elephant.png",
    "animals/cat.png",
    "animals/tiger.png",
    "animals/penguin.png",
    "animals/dear.png",
    "animals/fox.png",
    "animals/monkey.png",
    "animals/hippo.png",
    "animals/dolphin.png",
    "animals/zebra.png",
    "animals/tortuga.png",
    "animals/giraffe.png",
    "animals/lion.png",
    "animals/diano.png",
    "animals/rabbit.png",
    "animals/horse.png",
    "animals/kangaroo.png",
    "animals/sloth.png",
    "animals/hamster.png",
    "animals/raccoon.png",
    "animals/panda.png",
  ],
  fruits: [
    "fruits/apple.png",
    "fruits/avocado.png",
    "fruits/cherry.png",
    "fruits/mango.png",
    "fruits/grapes.png",
    "fruits/kiwi.png",
    "fruits/custard.png",
    "fruits/strawberry.png",
    "fruits/peach.png",
    "fruits/papaya.png",
    "fruits/blue-berry.png",
    "fruits/coconut.png",
    "fruits/watermelon.png",
    "fruits/pineapple.png",
    "fruits/dragon.png",
    "fruits/orange.png",
    "fruits/pomgranate.png",
    "fruits/plum.png",
    "fruits/melon.png",
    "fruits/star.png",
    "fruits/pears.png",
  ],
  cartoon: [
    "cartoons/bean.png",
    "cartoons/ben10.png",
    "cartoons/daisy.png",
    "cartoons/dora.png",
    "cartoons/doraemon.png",
    "cartoons/goofy.png",
    "cartoons/jack.png",
    "cartoons/jerry.png",
    "cartoons/micky.png",
    "cartoons/mini.png",
    "cartoons/minion.png",
    "cartoons/oggy.png",
    "cartoons/pikachu.png",
    "cartoons/shin.png",
    "cartoons/simpson.png",
    "cartoons/sonic.png",
    "cartoons/spider.png",
    "cartoons/tom.png",
    "cartoons/tri.png",
    "cartoons/woody.png",
  ],
  cards: [
    "cards/a.png",
    "cards/a1.png",
    "cards/a3.png",
    "cards/joker.jpg",
    "cards/2.png",
    "cards/3.jpg",
    "cards/4.png",
    "cards/5.png",
    "cards/6.png",
    "cards/7.png",
    "cards/7.jpg",
    "cards/8.png",
    "cards/8(2).png",
    "cards/9.png",
    "cards/9(2).png",
    "cards/q.png",
    "cards/k.png",
    "cards/j.png",
    "cards/j2.png",
    "cards/k3.png"
  ],
  cars: [
    "cars/car.png",
    "cars/car1.png",
    "cars/car3.png",
    "cars/car4.png",
    "cars/car5.png",
    "cars/car6.png",
    "cars/car7.png",
    "cars/car8.png",
    "cars/car9.png",
    "cars/car10.png",
    "cars/car11.png",
    "cars/car12.png",
    "cars/car13.png",
    "cars/car14.png",
    "cars/car15.png",
    "cars/car16.png",
    "cars/car17.png",
    "cars/car18.png",
    "cars/car19.png",
    "cars/car20.png",
    "cars/car21.png",
  ],
  mixed: [
    "animals/elephant.png",
    "animals/cat.png",
    "animals/tiger.png",
    "animals/penguin.png",
    "animals/dear.png",
    "animals/fox.png",
    "animals/monkey.png",
    "animals/hippo.png",
    "animals/dolphin.png",
    "animals/zebra.png",
    "animals/tortuga.png",
    "animals/giraffe.png",
    "animals/lion.png",
    "animals/diano.png",
    "animals/rabbit.png",
    "animals/horse.png",
    "animals/kangaroo.png",
    "animals/sloth.png",
    "animals/hamster.png",
    "animals/raccoon.png",
    "animals/panda.png",
    "fruits/apple.png",
    "fruits/avocado.png",
    "fruits/cherry.png",
    "fruits/mango.png",
    "fruits/grapes.png",
    "fruits/kiwi.png",
    "fruits/custard.png",
    "fruits/strawberry.png",
    "fruits/peach.png",
    "fruits/papaya.png",
    "fruits/blue-berry.png",
    "fruits/coconut.png",
    "fruits/watermelon.png",
    "fruits/pineapple.png",
    "fruits/dragon.png",
    "fruits/orange.png",
    "fruits/pomgranate.png",
    "fruits/plum.png",
    "fruits/melon.png",
    "fruits/star.png",
    "fruits/pears.png",
    "cartoons/bean.png",
    "cartoons/ben10.png",
    "cartoons/daisy.png",
    "cartoons/dora.png",
    "cartoons/doraemon.png",
    "cartoons/goofy.png",
    "cartoons/jack.png",
    "cartoons/jerry.png",
    "cartoons/micky.png",
    "cartoons/mini.png",
    "cartoons/minion.png",
    "cartoons/oggy.png",
    "cartoons/pikachu.png",
    "cartoons/shin.png",
    "cartoons/simpson.png",
    "cartoons/sonic.png",
    "cartoons/spider.png",
    "cartoons/tom.png",
    "cartoons/tri.png",
    "cartoons/woody.png",
    "cards/a.png",
    "cards/a1.png",
    "cards/a3.png",
    "cards/joker.jpg",
    "cards/2.png",
    "cards/3.jpg",
    "cards/4.png",
    "cards/5.png",
    "cards/6.png",
    "cards/7.png",
    "cards/7.jpg",
    "cards/8.png",
    "cards/8(2).png",
    "cards/9.png",
    "cards/9(2).png",
    "cards/q.png",
    "cards/k.png",
    "cards/j.png",
    "cards/j2.png",
    "cards/k3.png",
    "cars/car.png",
    "cars/car1.png",
    "cars/car3.png",
    "cars/car4.png",
    "cars/car5.png",
    "cars/car6.png",
    "cars/car7.png",
    "cars/car8.png",
    "cars/car9.png",
    "cars/car10.png",
    "cars/car11.png",
    "cars/car12.png",
    "cars/car13.png",
    "cars/car14.png",
    "cars/car15.png",
    "cars/car16.png",
    "cars/car17.png",
    "cars/car18.png",
    "cars/car19.png",
    "cars/car20.png",
    "cars/car21.png",
  ]
}


/** Same as memory-game-react `App.tsx` BOARD_CONFIG */
export const BOARD_CONFIG: Record<BoardSize, { cols: number; pairCount: number }> = {
  small: { cols: 4, pairCount: 6 },
  medium: { cols: 5, pairCount: 10 },
  large: { cols: 8, pairCount: 20 },
}

export const SMALL_SCREEN_MAX_WIDTH = 420
export const LARGE_COMPACT_CONFIG = { cols: 6, pairCount: 21 }

export function getBalancedColumns(totalCards: number, preferredCols: number): number {
  if (totalCards <= 0) return preferredCols

  let cols = Math.min(preferredCols, totalCards)
  while (cols > 2 && totalCards % cols === 1) {
    cols -= 1
  }

  return cols
}
export const PREVIEW_SETS: Record<Exclude<CardSetKey, "custom">, string> = {
  cards: "cards/a1.png",
  fruits: "fruits/apple.png",
  animals: "animals/elephant.png",
  cartoon: "cartoons/pikachu.png",
  cars: "cars/car.png",
  mixed: "animals/diano.png",
}

export const CARD_SET_ORDER: Exclude<CardSetKey, "custom">[] = [
  "cards",
  "fruits",
  "animals",
  "cartoon",
  "cars",
  "mixed",
]

export const CARD_SET_LABELS: Record<Exclude<CardSetKey, "custom">, string> = {
  cards: "Cards",
  fruits: "Fruits",
  animals: "Animals",
  cartoon: "Cartoon",
  cars: "Cars",
  mixed: "Mixed",
}

